[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "moove-voice-to-text"
version = "1.0"
description = "moove-voice-to-text: An agentic AI framework to help doctors take medical notes to aid diagnosis."
readme = "README.md"
requires-python = ">=3.10"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N"]
fixable = ["ALL"]
ignore = ["E501", "E402"]   # Avoid enforcing line-length violations (`E501`) and Module level import not at top of file (`E402`)

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"run_index_api.py" = ["N803", "N806"]